"""
##############################################################################
#████████╗██████╗ ██╗ ██████╗  ██████╗ ███████╗██████╗       ███████╗ ██████╗#
#╚══██╔══╝██╔══██╗██║██╔════╝ ██╔════╝ ██╔════╝██╔══██╗      ██╔════╝██╔════╝#
#   ██║   ██████╔╝██║██║  ███╗██║  ███╗█████╗  ██████╔╝█████╗███████╗██║     #
#   ██║   ██╔══██╗██║██║   ██║██║   ██║██╔══╝  ██╔══██╗╚════╝╚════██║██║     #
#   ██║   ██║  ██║██║╚██████╔╝╚██████╔╝███████╗██║  ██║      ███████║╚██████╗#
#   ╚═╝   ╚═╝  ╚═╝╚═╝ ╚═════╝  ╚═════╝ ╚══════╝╚═╝  ╚═╝      ╚══════╝ ╚═════╝#
#                                                                            #
#██╗  ██╗███╗   ██╗                                                          #
#██║  ██║████╗  ██║                                                          #
#███████║██╔██╗ ██║                                                          #
#╚════██║██║╚██╗██║                                                          #
#     ██║██║ ╚████║                                                          #
#     ╚═╝╚═╝  ╚═══╝                                                          #
#                                                                            #
##############################################################################
"""
/workflow/trigger-scan/policy_compliance/scans/subscription/$2y$07$Id3qWXJkjO2K4G6CoVjaM.r29x10m3ZsJKP7DkCePwPIN6RFYrG9O
...
[SCAN COMPLETE!]
# 在日誌中顯示資源的最新合規狀態。[logs] #
$ echo: "SCAN FAIL! NON COMPLIANCE RESOURCE use 'scopes-ignore input' "
$ ignore ['compliance status', 'resources']
# ...the compliance scan action will not upload a report to the workflow run
<br>
{
    "name": "Trigger Azure Policy Compliance Scan",
    "description": "Trigger an on-demand Azure policy compliance scan on a scope",
    "iconName": "azure",
    "categories": [
        "Deployment"
    ]
}
<br>
name: scan-subscription-without-report
on: push

jobs:
  assess-policy-compliance:    
    runs-on: ubuntu-latest
    steps:
    # Azure Login       
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}} 
    
    - name: Check for resource compliance
      uses: azure/policy-compliance-scan@v0
      with:
        scopes: |
          /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        skip-report: true
name: trigger_scan_on_scope
on:
  push:
    paths:
    - '**trigger-scan-on-scope.yml'
~
env:
  SCAN_SCOPE: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx    # set this to the scope that is to be scanned. It can be a Subscription, Resource group or a resource

jobs:
  assess-policy-compliance:    
    runs-on: ubuntu-latest
    steps:
    # Azure Login       
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}} 
    
    - name: Check for resource compliance
      uses: azure/policy-compliance-scan@v0
      with:
        scopes: ${{env.SCAN_SCOPE}}

# The compliance scan action will pass irrespective of the compliance status of scanned resources

name: scan-rg-ignore-compliance-status
on: push

jobs:
  assess-policy-compliance:    
    runs-on: ubuntu-latest
    steps:
    # Azure Login       
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}} 
    
    - name: Check for resource compliance
      uses: azure/policy-compliance-scan@v0
      with:
        scopes: |
          /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/my-Resource-Group/
        scopes-ignore: all
          /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/my-Resource-Group/providers/Microsoft.Web/sites/testApp
          /subscriptions/@@@@@@@@-@@@@-@@@@-@@@@-@@@@@@@@@@@@/resourceGroups/my-new-resource-group/providers/Microsoft.Web/sites/zenithWorksApp     
        wait: false
name: Multijob workflow to build and deploy Docker app to Azure
["碼頭工人"]
                                               .++++++=..                                           
                                               .#++*##*..                                           
                                     ...........#++*##*.                                            
                                   .------------#***##*.           ...:....                         
                                 .  #*+***#+++**#+**##*.           ..***-..                         
                               .....#****##++**##+**##*.....       .=#++**...  ..                   
                              ......#*****#+++**#****#*:......     .%*+++*#......                   
                              ***+***++++*#****##++**##**###=.     .=#++++##***##+.                 
                              ***+***+++*##+**###++*###**###=.     ..+*+++++++++*-.                 
                       .......***++**++++*#+****#+++**#+***#=.....-+**+++++*###-..                  
                        .#*+++++++++++++++++++++++++++++++++++++++++++++#..... ...                  
                 ....=:..#*++++++++++++++++**+++++++++**++++++++++++*++#:....-...                   
                 ..:=++++*########******########****########*****######+==+++++=...                 
                       ...#*******************************************:.                            
                       .. :#************+#-+***********************##..                             
                          .-#************==**********************##:...                             
                           .:**+*****+-=***********************#*-..                                
                            ..-+-:::::::-*******************#*=...                                  
                              ..:**-::::::-*************##+:.                                       
                                 ....####+=--+*######=....  .                                       
                           ....       ....... .....   ...                                           
                      .....=+:    .....     ......    :+-.      .  ...       .  ..                  
                      .....*%-   ......       ......  -%+. . .   ......        ....                 
                 . ..%####.*%-...-####*.......=####+..-%+..-#-. ..*###*:.......###-                 
                ..=##*..-+%#%-.-##+:.-###...=#*=..=*:.-%+:##+..:##*:.:+##:..-##*-..                 
                 -#*.. .. .#%-+#*. ....-##.-#=......  -%##+:...#*:. ..+##=.-##...                   
                .-#-      .*%-*#=    ...+#.+%-.       -%#*....:#*...+#*-...-#-. .                   
                 -%#......:%+.:#*......=##.:##:.....  -%###=...##**##..   .-#-.                     
                 .:*##*+*##+....###*=###+...-##%*+##=.-#+.*##:..*##*+*%#:..-#-.                     
                    .-+++:.    ...=+++:..   ...=++=:...=:..:+:....:+++-.. .:+:                      
on: push

env:
  CONTAINER_REGISTRY: akam.azurecr.io   # set this to Container Registry name

jobs:
  build-in-actions-workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
              
   # Authentication
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Build and push container
    - run: |
        docker build . -t ${{ env.CONTAINER_REGISTRY }}/nodejsapp:latest
        docker push ${{ env.CONTAINER_REGISTRY }}/nodejsapp:latest

  deploy-using-azure-pipelines:
    needs: build-in-actions-workflow
    runs-on: ubuntu-latest
    steps:
    - name: 'Trigger an Azure Pipeline to deploy the app to PRODUCTION'
      uses: Azure/pipelines@releases/v1
      with:
        azure-devops-project-url: 'https://dev.azure.com/OrganizationName/ProjectName'
        azure-pipeline-name: 'WebApp_Azure_Prod' 
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
